apiVersion: v1
kind: Pod
metadata: 
  name: javawebappTest
  labels:
   app: javawebappTest
  namespace: test-ns
spec:
   containers:
  - name: javawebapp1
    image: kkeducation123456/maven-web-app:1.2
    ports:
    - containerPort: 8080
