apiVersion: v1
kind: Pod
metadata: 
   name: mangodb-pod
   namespace: default
   labels:
    app: mangodb
spec:
  containers:
   -name: mangodb
    image: mongo:6.0
    ports:
     -containerPort: 27017
