apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: my_test
  labels: 
    app: tomcat
  spec:
    containers:
    -name: tomcat
     image: tomcat:9.0
     ports:
       -containerPort: 8080
